[package]
name = "wav_generator"
version = "0.1.0"
authors = ["Brenton <brenton@circalengineering.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sample = "0.10.0"
clap = "2.33.0"